CREATE TABLE IF NOT EXISTS app.providers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name text NOT NULL CHECK (btrim(display_name) <> ''),
    normalized_name text NOT NULL CHECK (btrim(normalized_name) <> ''),
    legal_name text,
    description text,
    phone text,
    email text,
    website text,
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app.provider_locations (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    provider_id bigint NOT NULL REFERENCES app.providers(id),
    place_id bigint NOT NULL REFERENCES app.places(id),
    is_primary boolean NOT NULL DEFAULT false,
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (provider_id, place_id)
);

CREATE TABLE IF NOT EXISTS app.service_types (
    id smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE CHECK (code ~ '^[a-z][a-z0-9_]*$'),
    name text NOT NULL CHECK (btrim(name) <> ''),
    category text NOT NULL CHECK (category IN (
        'beauty', 'automotive', 'fitness', 'health', 'professional', 'local_services'
    )),
    description text,
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app.provider_services (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    provider_id bigint NOT NULL REFERENCES app.providers(id),
    service_type_id smallint NOT NULL REFERENCES app.service_types(id),
    display_name text,
    description text,
    price_amount numeric(12, 2) CHECK (price_amount IS NULL OR price_amount >= 0),
    price_currency char(3),
    duration_minutes integer CHECK (duration_minutes IS NULL OR duration_minutes > 0),
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (
        (price_amount IS NULL AND price_currency IS NULL)
        OR (price_amount IS NOT NULL AND price_currency IS NOT NULL)
    ),
    UNIQUE (provider_id, service_type_id)
);

CREATE TABLE IF NOT EXISTS app.provider_sources (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    provider_id bigint NOT NULL REFERENCES app.providers(id),
    source_id smallint NOT NULL REFERENCES app.place_sources(id),
    external_id text NOT NULL CHECK (btrim(external_id) <> ''),
    source_place_id bigint NOT NULL REFERENCES app.places(id),
    imported_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (source_id, external_id),
    UNIQUE (provider_id, source_id, external_id)
);

CREATE TABLE IF NOT EXISTS app.provider_import_runs (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source_id smallint NOT NULL REFERENCES app.place_sources(id),
    completed_at timestamptz NOT NULL DEFAULT now(),
    candidate_places integer NOT NULL,
    active_providers integer NOT NULL,
    active_locations integer NOT NULL,
    active_services integer NOT NULL,
    skipped_places integer NOT NULL,
    duplicates_prevented integer NOT NULL
);

CREATE INDEX IF NOT EXISTS providers_normalized_name_idx
    ON app.providers (normalized_name) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS provider_locations_place_idx
    ON app.provider_locations (place_id) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS provider_locations_provider_idx
    ON app.provider_locations (provider_id) WHERE status = 'active';
CREATE UNIQUE INDEX IF NOT EXISTS provider_locations_one_primary_idx
    ON app.provider_locations (provider_id) WHERE is_primary AND status = 'active';
CREATE INDEX IF NOT EXISTS provider_services_provider_idx
    ON app.provider_services (provider_id) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS provider_services_type_idx
    ON app.provider_services (service_type_id) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS provider_sources_provider_idx
    ON app.provider_sources (provider_id);

INSERT INTO app.service_types (code, name, category, description)
VALUES
    ('haircut', 'Haircut', 'beauty', 'Hair cutting services.'),
    ('hair_styling', 'Hair styling', 'beauty', 'Hair styling services.'),
    ('beauty_treatment', 'Beauty treatment', 'beauty', 'General beauty treatments.'),
    ('massage', 'Massage', 'beauty', 'Massage services.'),
    ('vehicle_repair', 'Vehicle repair', 'automotive', 'Motor vehicle repair services.'),
    ('tyre_service', 'Tyre service', 'automotive', 'Tyre fitting and repair services.'),
    ('car_wash', 'Car wash', 'automotive', 'Vehicle washing services.'),
    ('gym_membership', 'Gym membership', 'fitness', 'Access to a fitness centre.'),
    ('group_fitness', 'Group fitness', 'fitness', 'Group exercise and fitness activities.'),
    ('sports_facility_access', 'Sports facility access', 'fitness', 'Access to a sports centre.'),
    ('dental_checkup', 'Dental checkup', 'health', 'General dental examination services.'),
    ('teeth_cleaning', 'Teeth cleaning', 'health', 'Preventive dental hygiene services.'),
    ('medical_consultation', 'Medical consultation', 'health', 'General clinical consultation.'),
    ('psychotherapy', 'Psychotherapy', 'health', 'Psychotherapy services.'),
    ('rehabilitation', 'Rehabilitation', 'health', 'Physical rehabilitation services.'),
    ('eye_exam', 'Eye exam', 'health', 'Optometry and eye examination services.'),
    ('veterinary_consultation', 'Veterinary consultation', 'health', 'Veterinary care services.'),
    ('accounting', 'Accounting', 'professional', 'Accounting services.'),
    ('legal_consultation', 'Legal consultation', 'professional', 'Legal advisory services.'),
    ('insurance_consultation', 'Insurance consultation', 'professional', 'Insurance advisory services.'),
    ('property_services', 'Property services', 'professional', 'Property agency services.'),
    ('photography', 'Photography', 'professional', 'Photography services.'),
    ('plumbing', 'Plumbing', 'local_services', 'Plumbing services.'),
    ('alterations', 'Clothing alterations', 'local_services', 'Tailoring and clothing alterations.'),
    ('shoe_repair', 'Shoe repair', 'local_services', 'Shoe repair services.'),
    ('laundry_service', 'Laundry service', 'local_services', 'Laundry and dry-cleaning services.'),
    ('pet_grooming', 'Pet grooming', 'local_services', 'Pet grooming services.')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    description = EXCLUDED.description,
    status = 'active',
    updated_at = now();
